Revert "Remove unused apps from manifest"
This reverts commit 04c0f18da72203acbc54f50ca012fee760591238.

Apps can not be just removed from manifest, because it will break
the build when referenced anywhere else, like:

error: frameworks/base/packages/CarSystemUI/Android.bp:16:1:
"CarSystemUI-core" depends on undefined module "CarNotificationLib"
ninja: build stopped: subcommand failed.

To reduce build packages we need another approach.
Revert to unbreak builds.

Change-Id: I41ddd028d194a148077c6b587ea299a99b0f902c
Signed-off-by: Alexander Martinz <amartinz@shiftphones.com>